[package]
name = "kernel-async"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../kernel" }
embedded-hal-async = "1.0.0"

[lints]
workspace = true
