[package]
name = "cortexm33"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../kernel" }
cortexm = { path = "../cortex-m" }
cortexv7m = { path = "../cortex-v7m" }

[lints]
workspace = true
