////////////////////////////////////////////////////////////////////////////////
// Autogenerated by svd2regs.py on 2026-07-06
//   svd2regs.py --svd STM32U545.svd --save fdcan.rs --group FDCAN

use kernel::utilities::registers::{
    self, register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly,
};
use kernel::utilities::StaticRef;

use core::cell::Cell;
use kernel::deferred_call::{DeferredCall, DeferredCallClient};
use kernel::hil::can::{self, StandardBitTiming};
use kernel::platform::chip::ClockInterface;
use kernel::utilities::cells::{OptionalCell, TakeCell};
use kernel::utilities::registers::interfaces::{ReadWriteable, Readable, Writeable};

pub const NBRP_MIN: u32 = 0;
pub const NBRP_MAX: u32 = 511;

register_structs! {
    /// FDCAN1_RAM
    pub FdcanRegisters {
        /// FDCAN Core Release Register
        (0x000 => fdcan_crel: ReadOnly<u32, FDCAN_CREL::Register>),
        /// FDCAN endian register
        (0x004 => fdcan_endn: ReadOnly<u32>),
        (0x008 => _reserved0),
        /// FDCAN Data Bit Timing and Prescaler
        (0x00C => fdcan_dbtp: ReadWrite<u32, FDCAN_DBTP::Register>),
        /// FDCAN Test Register
        (0x010 => fdcan_test: ReadWrite<u32, FDCAN_TEST::Register>),
        /// FDCAN RAM Watchdog Register
        (0x014 => fdcan_rwd: ReadWrite<u32, FDCAN_RWD::Register>),
        /// FDCAN CC Control Register
        (0x018 => fdcan_cccr: ReadWrite<u32, FDCAN_CCCR::Register>),
        /// FDCAN Nominal Bit Timing and Prescaler
        (0x01C => fdcan_nbtp: ReadWrite<u32, FDCAN_NBTP::Register>),
        /// FDCAN Timestamp Counter Configuration
        (0x020 => fdcan_tscc: ReadWrite<u32, FDCAN_TSCC::Register>),
        /// FDCAN Timestamp Counter Value
        (0x024 => fdcan_tscv: ReadWrite<u32>),
        /// FDCAN Timeout Counter Configuration
        (0x028 => fdcan_tocc: ReadWrite<u32, FDCAN_TOCC::Register>),
        /// FDCAN Timeout Counter Value
        (0x02C => fdcan_tocv: ReadWrite<u32>),
        (0x030 => _reserved1),
        /// FDCAN Error Counter Register
        (0x040 => fdcan_ecr: ReadWrite<u32, FDCAN_ECR::Register>),
        /// FDCAN Protocol Status Register
        (0x044 => fdcan_psr: ReadWrite<u32, FDCAN_PSR::Register>),
        /// FDCAN Transmitter Delay Compensation
        (0x048 => fdcan_tdcr: ReadWrite<u32, FDCAN_TDCR::Register>),
        (0x04C => _reserved2),
        /// FDCAN Interrupt Register
        (0x050 => fdcan_ir: ReadWrite<u32, FDCAN_IR::Register>),
        /// FDCAN Interrupt Enable
        (0x054 => fdcan_ie: ReadWrite<u32, FDCAN_IE::Register>),
        /// FDCAN Interrupt Line Select
        (0x058 => fdcan_ils: ReadWrite<u32, FDCAN_ILS::Register>),
        /// FDCAN Interrupt Line Enable
        (0x05C => fdcan_ile: ReadWrite<u32, FDCAN_ILE::Register>),
        (0x060 => _reserved3),
        /// FDCAN Global Filter Configuration
        (0x080 => fdcan_rxgfc: ReadWrite<u32, FDCAN_RXGFC::Register>),
        /// FDCAN Extended ID and Mask
        (0x084 => fdcan_xidam: ReadWrite<u32>),
        /// FDCAN High Priority Message Status
        (0x088 => fdcan_hpms: ReadOnly<u32, FDCAN_HPMS::Register>),
        (0x08C => _reserved4),
        /// FDCAN Rx FIFO 0 Status
        (0x090 => fdcan_rxf0s: ReadOnly<u32, FDCAN_RXF0S::Register>),
        /// CAN Rx FIFO 0 Acknowledge
        (0x094 => fdcan_rxf0a: ReadWrite<u32>),
        /// FDCAN Rx FIFO 1 Status
        (0x098 => fdcan_rxf1s: ReadOnly<u32, FDCAN_RXF1S::Register>),
        /// FDCAN Rx FIFO 1 Acknowledge
        (0x09C => fdcan_rxf1a: ReadWrite<u32>),
        (0x0A0 => _reserved5),
        /// FDCAN Tx buffer configuration register
        (0x0C0 => fdcan_txbc: ReadWrite<u32, FDCAN_TXBC::Register>),
        /// FDCAN Tx FIFO/Queue Status
        (0x0C4 => fdcan_txfqs: ReadOnly<u32, FDCAN_TXFQS::Register>),
        /// FDCAN Tx Buffer Request Pending
        (0x0C8 => fdcan_txbrp: ReadOnly<u32>),
        /// FDCAN Tx Buffer Add Request
        (0x0CC => fdcan_txbar: ReadWrite<u32>),
        /// FDCAN Tx Buffer Cancellation Request
        (0x0D0 => fdcan_txbcr: ReadWrite<u32>),
        /// FDCAN Tx Buffer Transmission Occurred
        (0x0D4 => fdcan_txbto: ReadOnly<u32>),
        /// FDCAN Tx Buffer Cancellation Finished
        (0x0D8 => fdcan_txbcf: ReadOnly<u32>),
        /// FDCAN Tx Buffer Transmission Interrupt
        (0x0DC => fdcan_txbtie: ReadWrite<u32>),
        /// FDCAN Tx Buffer Cancellation Finished
        (0x0E0 => fdcan_txbcie: ReadWrite<u32>),
        /// FDCAN Tx Event FIFO Status
        (0x0E4 => fdcan_txefs: ReadOnly<u32, FDCAN_TXEFS::Register>),
        /// FDCAN Tx Event FIFO Acknowledge
        (0x0E8 => fdcan_txefa: ReadWrite<u32>),
        (0x0EC => _reserved6),
        /// FDCAN CFG clock divider register
        (0x100 => fdcan_ckdiv: ReadWrite<u32>),
        (0x104 => @END),
    }
}
register_bitfields![u32,
FDCAN_CREL [
    /// Core release
    REL OFFSET(28) NUMBITS(4) [],
    /// Step of Core release
    STEP OFFSET(24) NUMBITS(4) [],
    /// Sub-step of Core release
    SUBSTEP OFFSET(20) NUMBITS(4) [],
    /// Timestamp Year
    YEAR OFFSET(16) NUMBITS(4) [],
    /// Timestamp Month
    MON OFFSET(8) NUMBITS(8) [],
    /// Timestamp Day
    DAY OFFSET(0) NUMBITS(8) []
],
FDCAN_ENDN [
    /// Endiannes Test Value
    ETV OFFSET(0) NUMBITS(32) []
],
FDCAN_DBTP [
    /// Synchronization Jump Width
    DSJW OFFSET(0) NUMBITS(4) [],
    /// Data time segment after sample
    DTSEG2 OFFSET(4) NUMBITS(4) [],
    /// Data time segment after sample
    DTSEG1 OFFSET(8) NUMBITS(5) [],
    /// Data BIt Rate Prescaler
    DBRP OFFSET(16) NUMBITS(5) [],
    /// Transceiver Delay
    TDC OFFSET(23) NUMBITS(1) []
],
FDCAN_TEST [
    /// Loop Back mode
    LBCK OFFSET(4) NUMBITS(1) [],
    // TX Pin control
    TX OFFSET(5) NUMBITS(2) [
        CAN_CORE = 0,
        SP = 1,
        DOMINANT = 2,
        RECESSIVE = 3,
    ],
    /// Control of Transmit Pin
    RX OFFSET(7) NUMBITS(1) []
],
FDCAN_RWD [
    /// Watchdog value
    WDV OFFSET(8) NUMBITS(8) [],
    /// Watchdog configuration
    WDC OFFSET(0) NUMBITS(8) []
],
FDCAN_CCCR [
    /// Initialization
    INIT OFFSET(0) NUMBITS(1) [],
    /// Configuration Change
    CCE OFFSET(1) NUMBITS(1) [],
    /// ASM Restricted Operation
    ASM OFFSET(2) NUMBITS(1) [],
    /// Clock Stop Acknowledge
    CSA OFFSET(3) NUMBITS(1) [],
    /// Clock Stop Request
    CSR OFFSET(4) NUMBITS(1) [],
    /// Bus Monitoring Mode
    MON OFFSET(5) NUMBITS(1) [],
    /// Disable Automatic
    DAR OFFSET(6) NUMBITS(1) [],
    /// Test Mode Enable
    TEST OFFSET(7) NUMBITS(1) [],
    /// FD Operation Enable
    FDOE OFFSET(8) NUMBITS(1) [],
    /// FDCAN Bit Rate Switching
    BRSE OFFSET(9) NUMBITS(1) [],
    /// Protocol Exception Handling
    PXHD OFFSET(12) NUMBITS(1) [],
    /// Edge Filtering during Bus
    EFBI OFFSET(13) NUMBITS(1) [],
    /// TXP
    TXP OFFSET(14) NUMBITS(1) [],
    /// Non ISO Operation
    NISO OFFSET(15) NUMBITS(1) []
],
FDCAN_NBTP [
    /// Nominal (Re)Synchronization Jump
    NSJW OFFSET(25) NUMBITS(7) [],
    /// Bit Rate Prescaler
    NBRP OFFSET(16) NUMBITS(9) [],
    /// Nominal Time segment before sample
    NTSEG1 OFFSET(8) NUMBITS(8) [],
    /// Nominal Time segment after sample
    NTSEG2 OFFSET(0) NUMBITS(7) []
],
FDCAN_TSCC [
    /// Timestamp Counter
    TCP OFFSET(16) NUMBITS(4) [],
    /// Timestamp Select
    TSS OFFSET(0) NUMBITS(2) []
],
FDCAN_TSCV [
    /// Timestamp Counter
    TSC OFFSET(0) NUMBITS(16) []
],
FDCAN_TOCC [
    /// Enable Timeout Counter
    ETOC OFFSET(0) NUMBITS(1) [],
    /// Timeout Select
    TOS OFFSET(1) NUMBITS(2) [],
    /// Timeout Period
    TOP OFFSET(16) NUMBITS(16) []
],
FDCAN_TOCV [
    /// Timeout Counter
    TOC OFFSET(0) NUMBITS(16) []
],
FDCAN_ECR [
    /// AN Error Logging
    CEL OFFSET(16) NUMBITS(8) [],
    /// Receive Error Passive
    RP OFFSET(15) NUMBITS(1) [],
    /// Receive Error Counter
    REC OFFSET(8) NUMBITS(7) [],
    /// Transmit Error Counter
    TEC OFFSET(0) NUMBITS(8) []
],
FDCAN_PSR [
    /// Last Error Code
    LEC OFFSET(0) NUMBITS(3) [],
    /// Activity
    ACT OFFSET(3) NUMBITS(2) [],
    /// Error Passive
    EP OFFSET(5) NUMBITS(1) [],
    /// Warning Status
    EW OFFSET(6) NUMBITS(1) [],
    /// Bus_Off Status
    BO OFFSET(7) NUMBITS(1) [],
    /// Data Last Error Code
    DLEC OFFSET(8) NUMBITS(3) [],
    /// ESI flag of last received FDCAN
    RESI OFFSET(11) NUMBITS(1) [],
    /// BRS flag of last received FDCAN
    RBRS OFFSET(12) NUMBITS(1) [],
    /// Received FDCAN Message
    REDL OFFSET(13) NUMBITS(1) [],
    /// Protocol Exception Event
    PXE OFFSET(14) NUMBITS(1) [],
    /// Transmitter Delay Compensation
    TDCV OFFSET(16) NUMBITS(7) []
],
FDCAN_TDCR [
    /// Transmitter Delay Compensation Filter
    TDCF OFFSET(0) NUMBITS(7) [],
    /// Transmitter Delay Compensation
    TDCO OFFSET(8) NUMBITS(7) []
],
FDCAN_IR [
    /// RF0N
    RF0N OFFSET(0) NUMBITS(1) [],
    /// RF0F
    RF0F OFFSET(1) NUMBITS(1) [],
    /// RF0L
    RF0L OFFSET(2) NUMBITS(1) [],
    /// RF1N
    RF1N OFFSET(3) NUMBITS(1) [],
    /// RF1F
    RF1F OFFSET(4) NUMBITS(1) [],
    /// RF1L
    RF1L OFFSET(5) NUMBITS(1) [],
    /// HPM
    HPM OFFSET(6) NUMBITS(1) [],
    /// TC
    TC OFFSET(7) NUMBITS(1) [],
    /// TCF
    TCF OFFSET(8) NUMBITS(1) [],
    /// TFE
    TFE OFFSET(9) NUMBITS(1) [],
    /// TEFN
    TEFN OFFSET(10) NUMBITS(1) [],
    /// TEFF
    TEFF OFFSET(11) NUMBITS(1) [],
    /// TEFL
    TEFL OFFSET(12) NUMBITS(1) [],
    /// TSW
    TSW OFFSET(13) NUMBITS(1) [],
    /// MRAF
    MRAF OFFSET(14) NUMBITS(1) [],
    /// TOO
    TOO OFFSET(15) NUMBITS(1) [],
    /// ELO
    ELO OFFSET(16) NUMBITS(1) [],
    /// EP
    EP OFFSET(17) NUMBITS(1) [],
    /// EW
    EW OFFSET(18) NUMBITS(1) [],
    /// BO
    BO OFFSET(19) NUMBITS(1) [],
    /// WDI
    WDI OFFSET(20) NUMBITS(1) [],
    /// PEA
    PEA OFFSET(21) NUMBITS(1) [],
    /// PED
    PED OFFSET(22) NUMBITS(1) [],
    /// ARA
    ARA OFFSET(23) NUMBITS(1) []
],
FDCAN_IE [
    /// Rx FIFO 0 New Message
    RF0NE OFFSET(0) NUMBITS(1) [],
    /// Rx FIFO 0 Full Enable
    RF0FE OFFSET(1) NUMBITS(1) [],
    /// Rx FIFO 0 Message Lost
    RF0LE OFFSET(2) NUMBITS(1) [],
    /// Rx FIFO 1 New Message
    RF1NE OFFSET(3) NUMBITS(1) [],
    /// Rx FIFO 1 Watermark Reached
    RF1FE OFFSET(4) NUMBITS(1) [],
    /// Rx FIFO 1 Message Lost
    RF1LE OFFSET(5) NUMBITS(1) [],
    /// High Priority Message
    HPME OFFSET(6) NUMBITS(1) [],
    /// Transmission Completed
    TCE OFFSET(7) NUMBITS(1) [],
    /// Transmission Cancellation Finished
    TCFE OFFSET(8) NUMBITS(1) [],
    /// Tx FIFO Empty Enable
    TEFE OFFSET(9) NUMBITS(1) [],
    /// Tx Event FIFO New Entry
    TEFNE OFFSET(10) NUMBITS(1) [],
    /// Tx Event FIFO Full Enable
    TEFFE OFFSET(11) NUMBITS(1) [],
    /// Tx Event FIFO Element Lost
    TEFLE OFFSET(12) NUMBITS(1) [],
    /// TSWE
    TSWE OFFSET(13) NUMBITS(1) [],
    /// Message RAM Access Failure
    MRAFE OFFSET(14) NUMBITS(1) [],
    /// Timeout Occurred Enable
    TOOE OFFSET(15) NUMBITS(1) [],
    /// Error Logging Overflow
    ELOE OFFSET(16) NUMBITS(1) [],
    /// Error Passive Enable
    EPE OFFSET(17) NUMBITS(1) [],
    /// Warning Status Enable
    EWE OFFSET(18) NUMBITS(1) [],
    /// Bus_Off Status Enable
    BOE OFFSET(19) NUMBITS(1) [],
    /// Watchdog Interrupt Enable
    WDIE OFFSET(20) NUMBITS(1) [],
    /// Protocol Error in Arbitration Phase
    PEAE OFFSET(21) NUMBITS(1) [],
    /// Protocol Error in Data Phase
    PEDE OFFSET(22) NUMBITS(1) [],
    /// Access to Reserved Address
    ARAE OFFSET(23) NUMBITS(1) []
],
FDCAN_ILS [
    /// RxFIFO0
    RxFIFO0 OFFSET(0) NUMBITS(1) [],
    /// RxFIFO1
    RxFIFO1 OFFSET(1) NUMBITS(1) [],
    /// SMSG
    SMSG OFFSET(2) NUMBITS(1) [],
    /// TFERR
    TFERR OFFSET(3) NUMBITS(1) [],
    /// MISC
    MISC OFFSET(4) NUMBITS(1) [],
    /// BERR
    BERR OFFSET(5) NUMBITS(1) [],
    /// PERR
    PERR OFFSET(6) NUMBITS(1) []
],
FDCAN_ILE [
    /// Enable Interrupt Line 0
    EINT0 OFFSET(0) NUMBITS(1) [],
    /// Enable Interrupt Line 1
    EINT1 OFFSET(1) NUMBITS(1) []
],
FDCAN_RXGFC [
    /// Reject Remote Frames
    RRFE OFFSET(0) NUMBITS(1) [],
    /// Reject Remote Frames
    RRFS OFFSET(1) NUMBITS(1) [],
    /// Accept Non-matching Frames
    ANFE OFFSET(2) NUMBITS(2) [
        ACCEPT_FIFO0 = 0,
        ACCEPT_FIFO1 = 1,
        REJECT = 2
    ],
    /// Accept Non-matching Frames
    ANFS OFFSET(4) NUMBITS(2) [
        ACCEPT_FIFO0 = 0,
        ACCEPT_FIFO1 = 1,
        REJECT = 2
    ],
    /// F1OM
    F1OM OFFSET(8) NUMBITS(1) [],
    /// F0OM
    F0OM OFFSET(9) NUMBITS(1) [],
    /// LSS
    LSS OFFSET(16) NUMBITS(5) [],
    /// LSE
    LSE OFFSET(24) NUMBITS(4) []
],
FDCAN_XIDAM [
    /// Extended ID Mask
    EIDM OFFSET(0) NUMBITS(29) []
],
FDCAN_HPMS [
    /// Buffer Index
    BIDX OFFSET(0) NUMBITS(3) [],
    /// Message Storage Indicator
    MSI OFFSET(6) NUMBITS(2) [],
    /// Filter Index
    FIDX OFFSET(8) NUMBITS(5) [],
    /// Filter List
    FLST OFFSET(15) NUMBITS(1) []
],
FDCAN_RXF0S [
    /// Rx FIFO 0 Fill Level
    F0FL OFFSET(0) NUMBITS(4) [],
    /// Rx FIFO 0 Get Index
    F0GI OFFSET(8) NUMBITS(2) [],
    /// Rx FIFO 0 Put Index
    F0PI OFFSET(16) NUMBITS(2) [],
    /// Rx FIFO 0 Full
    F0F OFFSET(24) NUMBITS(1) [],
    /// Rx FIFO 0 Message Lost
    RF0L OFFSET(25) NUMBITS(1) []
],
FDCAN_RXF0A [
    /// Rx FIFO 0 Acknowledge
    F0AI OFFSET(0) NUMBITS(3) []
],
FDCAN_RXF1S [
    /// Rx FIFO 1 Fill Level
    F1FL OFFSET(0) NUMBITS(4) [],
    /// Rx FIFO 1 Get Index
    F1GI OFFSET(8) NUMBITS(2) [],
    /// Rx FIFO 1 Put Index
    F1PI OFFSET(16) NUMBITS(2) [],
    /// Rx FIFO 1 Full
    F1F OFFSET(24) NUMBITS(1) [],
    /// Rx FIFO 1 Message Lost
    RF1L OFFSET(25) NUMBITS(1) []
],
FDCAN_RXF1A [
    /// Rx FIFO 1 Acknowledge
    F1AI OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBC [
    /// Tx FIFO/Queue Mode
    TFQM OFFSET(24) NUMBITS(1) []
],
FDCAN_TXFQS [
    /// Tx FIFO Free Level
    TFFL OFFSET(0) NUMBITS(3) [],
    /// TFGI
    TFGI OFFSET(8) NUMBITS(2) [],
    /// Tx FIFO/Queue Put Index
    TFQPI OFFSET(16) NUMBITS(2) [],
    /// Tx FIFO/Queue Full
    TFQF OFFSET(21) NUMBITS(1) []
],
FDCAN_TXBRP [
    /// Transmission Request
    TRP OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBAR [
    /// Add Request
    AR OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBCR [
    /// Cancellation Request
    CR OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBTO [
    /// Transmission Occurred.
    TO OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBCF [
    /// Cancellation Finished
    CF OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBTIE [
    /// Transmission Interrupt
    TIE OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBCIE [
    /// Cancellation Finished Interrupt
    CFIE OFFSET(0) NUMBITS(3) []
],
FDCAN_TXEFS [
    /// Event FIFO Fill Level
    EFFL OFFSET(0) NUMBITS(3) [],
    /// Event FIFO Get Index.
    EFGI OFFSET(8) NUMBITS(2) [],
    /// Event FIFO Put Index
    EFPI OFFSET(16) NUMBITS(2) [],
    /// Event FIFO Full.
    EFF OFFSET(24) NUMBITS(1) [],
    /// Tx Event FIFO Element
    TEFL OFFSET(25) NUMBITS(1) []
],
FDCAN_TXEFA [
    /// Event FIFO Acknowledge
    EFAI OFFSET(0) NUMBITS(2) []
],
FDCAN_CKDIV [
    /// PDIV
    PDIV OFFSET(0) NUMBITS(4) []
]
];
pub const FDCAN1_RAM_BASE: StaticRef<Fdcan1MessageRam> =
    unsafe { StaticRef::new(0x4000AC00 as *const Fdcan1MessageRam) };

pub const SEC_FDCAN1_RAM_BASE: StaticRef<Fdcan1MessageRam> =
    unsafe { StaticRef::new(0x5000AC00 as *const Fdcan1MessageRam) };

pub const FDCAN1_BASE: StaticRef<FdcanRegisters> =
    unsafe { StaticRef::new(0x4000A400 as *const FdcanRegisters) };

pub const SEC_FDCAN1_BASE: StaticRef<FdcanRegisters> =
    unsafe { StaticRef::new(0x5000A400 as *const FdcanRegisters) };

// End autogenerated block
////////////////////////////////////////////////////////////////////////////////

type Registers = FdcanRegisters;

#[derive(Copy, Clone, PartialEq)]
enum CanState {
    Initialization,
    Normal,
    Sleep,
    RunningError(can::Error),
}

#[derive(Copy, Clone, PartialEq)]
enum AsyncAction {
    Enable,
    AbortReceive,
    Disabled,
    EnableError(kernel::ErrorCode),
}

#[repr(u32)]
enum BitSegment1 {
    CanBtrTs1Min = 0b0000,
    CanBtrTs1Max = 0b1111,
}

#[repr(u32)]
enum BitSegment2 {
    CanBtrTs2Min = 0b0000,
    CanBtrTs2Max = 0b0111,
}

#[repr(u32)]
enum SynchronizationJumpWidth {
    CanBtrSjwMin = 0b00,
    CanBtrSjwMax = 0b11,
}

#[derive(Copy, Clone, PartialEq)]
pub enum CanInterruptMode {
    TransmitInterrupt,
    Fifo0Interrupt,
    Fifo1Interrupt,
    ErrorAndStatusChangeInterrupt,
}

impl From<CanState> for can::State {
    fn from(state: CanState) -> Self {
        match state {
            CanState::Initialization | CanState::Sleep => can::State::Disabled,
            CanState::Normal => can::State::Running,
            CanState::RunningError(err) => can::State::Error(err),
        }
    }
}

pub struct Can {
    registers: StaticRef<Registers>,
    enable_clock: fn(),
    can_state: Cell<CanState>,
    error_interrupt_counter: Cell<u32>,
    failed_messages: Cell<u32>,

    // communication params
    automatic_retransmission: Cell<bool>,
    //automatic_wake_up: Cell<bool>,
    operating_mode: OptionalCell<can::OperationMode>,
    bit_timing: OptionalCell<can::BitTiming>,

    // clients
    controller_client: OptionalCell<&'static dyn can::ControllerClient>,
    receive_client:
        OptionalCell<&'static dyn can::ReceiveClient<{ can::STANDARD_CAN_PACKET_SIZE }>>,
    transmit_client:
        OptionalCell<&'static dyn can::TransmitClient<{ can::STANDARD_CAN_PACKET_SIZE }>>,

    //buffers
    rx_buffer: TakeCell<'static, [u8; can::STANDARD_CAN_PACKET_SIZE]>,
    tx_buffer: TakeCell<'static, [u8; can::STANDARD_CAN_PACKET_SIZE]>,

    deferred_call: DeferredCall,

    //deffered call action task
    deferred_action: OptionalCell<AsyncAction>,

    msg_ram: StaticRef<Fdcan1MessageRam>,
}

impl Can {
    pub fn new(
        registers: StaticRef<Registers>,
        msg_ram: StaticRef<Fdcan1MessageRam>,
        enable_clock: fn(),
    ) -> Can {
        Can {
            registers,
            enable_clock,
            can_state: Cell::new(CanState::Sleep),
            error_interrupt_counter: Cell::new(0),
            failed_messages: Cell::new(0),
            automatic_retransmission: Cell::new(false),
            //automatic_wake_up: Cell::new(false),
            operating_mode: OptionalCell::empty(),
            bit_timing: OptionalCell::empty(),
            controller_client: OptionalCell::empty(),
            receive_client: OptionalCell::empty(),
            transmit_client: OptionalCell::empty(),
            rx_buffer: TakeCell::empty(),
            tx_buffer: TakeCell::empty(),
            deferred_call: DeferredCall::new(),
            deferred_action: OptionalCell::empty(),
            msg_ram,
        }
    }

    /// This function is used for busy waiting and checks if the closure
    /// received as an argument returns a true value for `times` times.
    ///
    /// Usage: check is the INIT bit in the FDCAN_CCCR is set for 200_000 times
    /// ```ignore
    ///    Can::wait_for(200_000, || self.registers.can_msr.is_set(CAN_MSR::INAK))
    /// ```
    fn wait_for(times: usize, f: impl Fn() -> bool) -> bool {
        for _ in 0..times {
            if f() {
                return true;
            }
        }

        false
    }

    pub fn enable(&self) -> Result<(), kernel::ErrorCode> {
        //initialize the peripheral
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::INIT::SET);
        //we wait for init to be written as specified in rm0456 70.4.5
        if !Can::wait_for(20000, || self.registers.fdcan_cccr.is_set(FDCAN_CCCR::INIT)) {
            return Err(kernel::ErrorCode::FAIL);
        }
        //configuration change enable register
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::CCE::SET);

        self.can_state.set(CanState::Initialization);

        //we are doing a standard CAN driver for now, just making sure
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::FDOE::CLEAR);

        // here we set it to overwrite if full on both RX FIFOs
        self.registers.fdcan_rxgfc.modify(FDCAN_RXGFC::F0OM::SET);
        self.registers.fdcan_rxgfc.modify(FDCAN_RXGFC::F1OM::SET);

        //set transmit order priority (fifo vs queue)
        self.registers.fdcan_txbc.modify(FDCAN_TXBC::TFQM::SET);

        match self.automatic_retransmission.get() {
            true => self.registers.fdcan_cccr.modify(FDCAN_CCCR::DAR::CLEAR),
            false => self.registers.fdcan_cccr.modify(FDCAN_CCCR::DAR::SET),
        }

        if let Some(operating_mode_settings) = self.operating_mode.get() {
            match operating_mode_settings {
                can::OperationMode::Monitoring => {
                    self.registers.fdcan_cccr.modify(FDCAN_CCCR::MON::SET)
                }
                can::OperationMode::Loopback => {
                    self.registers.fdcan_cccr.modify(FDCAN_CCCR::TEST::SET);
                    self.registers.fdcan_test.modify(FDCAN_TEST::LBCK::SET);
                    self.registers.fdcan_cccr.modify(FDCAN_CCCR::MON::SET);
                }
                can::OperationMode::Freeze => return Err(kernel::ErrorCode::INVAL),
                _ => {}
            }
        }

        //we set bit timing mode
        if let Some(bit_timing_settings) = self.bit_timing.get() {
            self.registers
                .fdcan_nbtp
                .modify(FDCAN_NBTP::NTSEG1.val(bit_timing_settings.segment1 as u32));
            self.registers
                .fdcan_nbtp
                .modify(FDCAN_NBTP::NTSEG2.val(bit_timing_settings.segment2 as u32));
            self.registers
                .fdcan_nbtp
                .modify(FDCAN_NBTP::NSJW.val(bit_timing_settings.sync_jump_width as u32));
            self.registers
                .fdcan_nbtp
                .modify(FDCAN_NBTP::NBRP.val(bit_timing_settings.baud_rate_prescaler as u32));
        } else {
            self.disable();
            return Err(kernel::ErrorCode::INVAL);
        }

        Ok(())
    }

    pub fn config_filter(
        &self,
        filter_info: can::FilterParameters,
        enable: bool,
    ) -> Result<(), kernel::ErrorCode> {
        //the u5 has 28 standard filters and 8 extended filters. accessible in message
        // ram. for our purposes we use the standard ones

        // note: the FilterParameters struct doesn't provide any ID?! on the old f4
        // this function set up all the filter parameters except id, which was set to
        // let everything through?! unlike the f4,. we dont need to do that to receive
        // messages. so this function kinda remains empty for now, until the HIL is updated, we write into rxgfc to allow EVERYTHING to go to fifo0
        if filter_info.number >= 28 {
            return Err(kernel::ErrorCode::INVAL);
        }

        self.registers
            .fdcan_rxgfc
            .modify(FDCAN_RXGFC::ANFS::ACCEPT_FIFO0);
        self.registers
            .fdcan_rxgfc
            .modify(FDCAN_RXGFC::ANFE::ACCEPT_FIFO0);

        /*self.fdcan1messageram.flssa[filter_info.number as usize].write(

        )*/
        Ok(())
    }

    pub fn enable_filter_config(&self) {
        //nop
    }

    pub fn enter_normal_mode(&self) -> Result<(), kernel::ErrorCode> {
        //clear init which automatically clears CCE (we disable configuration) and then wait
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::INIT::CLEAR);
        if !Can::wait_for(20000, || {
            !self.registers.fdcan_cccr.is_set(FDCAN_CCCR::INIT)
        }) {
            return Err(kernel::ErrorCode::FAIL);
        }

        //move the FSM to Normal
        self.can_state.set(CanState::Normal);

        Ok(())
    }

    pub fn disable(&self) {
        // equivalent to enter_sleep_mode in the f4 driver, we could also stop the clock
        // with CSA but that only brings a bit of power savings in exchange for
        // potential bugs, so i'll do it later
        // setting init stops the peripheral from going on the bus, which is similar behavior to sleep on the bxCAN f4 peripheral
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::INIT::SET);
        self.can_state.set(CanState::Sleep);
    }

    pub fn enable_irq(&self, interrupt: CanInterruptMode) {
        match interrupt {
            CanInterruptMode::TransmitInterrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::TEFE::SET);
            }
            CanInterruptMode::Fifo0Interrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::RF0NE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF0FE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF0LE::SET);
            }
            CanInterruptMode::Fifo1Interrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::RF1NE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF1FE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF1LE::SET);
            }
            CanInterruptMode::ErrorAndStatusChangeInterrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::EPE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::EWE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::BOE::SET);
                self.registers.fdcan_ie.modify(FDCAN_IE::MRAFE::SET);
            }
        }
    }

    pub fn disable_irq(&self, interrupt: CanInterruptMode) {
        match interrupt {
            CanInterruptMode::TransmitInterrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::TEFE::CLEAR);
            }
            CanInterruptMode::Fifo0Interrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::RF0NE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF0FE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF0LE::CLEAR);
            }
            CanInterruptMode::Fifo1Interrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::RF1NE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF1FE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::RF1LE::CLEAR);
            }
            CanInterruptMode::ErrorAndStatusChangeInterrupt => {
                self.registers.fdcan_ie.modify(FDCAN_IE::EPE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::EWE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::BOE::CLEAR);
                self.registers.fdcan_ie.modify(FDCAN_IE::MRAFE::CLEAR);
            }
        }
    }

    pub fn enable_irqs(&self) {
        self.enable_irq(CanInterruptMode::TransmitInterrupt);
        self.enable_irq(CanInterruptMode::Fifo0Interrupt);
        self.enable_irq(CanInterruptMode::Fifo1Interrupt);
        self.enable_irq(CanInterruptMode::ErrorAndStatusChangeInterrupt);
    }

    pub fn disable_irqs(&self) {
        self.disable_irq(CanInterruptMode::TransmitInterrupt);
        self.disable_irq(CanInterruptMode::Fifo0Interrupt);
        self.disable_irq(CanInterruptMode::Fifo1Interrupt);
        self.disable_irq(CanInterruptMode::ErrorAndStatusChangeInterrupt);
    }

    pub fn send_8byte_message(
        &self,
        id: can::Id,
        dlc: usize,
        rtr: u8,
    ) -> Result<(), kernel::ErrorCode> {
        if self.can_state.get() == CanState::Normal {
            self.enable_irqs();
            if self.registers.fdcan_txfqs.is_set(FDCAN_TXFQS::TFQF) {
                return Err(kernel::ErrorCode::BUSY);
            }

            //get the index of the free space in message ram where we have to store the message
            let put_index = self.registers.fdcan_txfqs.read(FDCAN_TXFQS::TFQPI) as usize;

            //compute where to put the data

            //compute the t0 header
            let mut t0 = match id {
                can::Id::Standard(id) => TX_ELEMENT_T0::ID.val((id as u32) << 18),
                can::Id::Extended(id) => TX_ELEMENT_T0::XTD::SET + TX_ELEMENT_T0::ID.val(id),
            };

            //set the rtr bit (weird that its u8 in the api)
            t0 += TX_ELEMENT_T0::RTR.val(rtr.into());

            let t1 = TX_ELEMENT_T1::DLC.val((dlc as u32));

            //write the data itself
            let words = self.tx_buffer.map(|tx| {
                let word0 = (tx[0] as u32)
                    | ((tx[1] as u32) << 8)
                    | ((tx[2] as u32) << 16)
                    | ((tx[3] as u32) << 24);
                let word1 = (tx[4] as u32)
                    | ((tx[5] as u32) << 8)
                    | ((tx[6] as u32) << 16)
                    | ((tx[7] as u32) << 24);
                (word0, word1)
            });
            let (word0, word1) = match words {
                Some(w) => w,
                None => return Err(kernel::ErrorCode::FAIL),
            };

            //put data in msgbuf
            let element = &self.msg_ram.tx_buffers[put_index];
            element.t0.write(t0);
            element.t1.write(t1);
            element.data[0].set(word0);
            element.data[1].set(word1);

            //request transfer
            self.registers.fdcan_txbar.set(1 << put_index);
            Ok(())
        } else {
            Err(kernel::ErrorCode::OFF)
        }
    }

    pub fn handle_transmit_interrupt(&self) {
        let mut state = Ok(());
        //we check if we received a request for a transition to bus off
        if self.registers.fdcan_ir.is_set(FDCAN_IR::BO) {
            state = Err(can::Error::BusOff)
        }
        if let Err(err) = state {
            self.can_state.set(CanState::RunningError(err));
        }

        self.transmit_client.map(|client| {
            if let Some(buf) = self.tx_buffer.take() {
                client.transmit_complete(state, buf);
            }
        });
    }

    pub fn handle_interrupt(&self) {
        let ir = self.registers.fdcan_ir.extract();
        if ir.is_set(FDCAN_IR::TC) {
            self.handle_transmit_interrupt();
        }
        if ir.is_set(FDCAN_IR::RF0N) {
            self.handle_fifo0_interrupt();
        }
        self.registers.fdcan_ir.set(ir.get());
    }

    pub fn handle_fifo0_interrupt(&self) {
        let get_index = self.registers.fdcan_rxf0s.read(FDCAN_RXF0S::F0GI);
        //let put_index = self.registers.fdcan_rxf0s.read(FDCAN_RXF0S::F0PI);
        let element = &self.msg_ram.rx_fifo0[get_index as usize];

        let r0 = element.r0.extract();
        let r1 = element.r1.extract();

        let xtd = r0.is_set(RX_ELEMENT_R0::XTD);
        let dlc = r1.read(RX_ELEMENT_R1::DLC) as usize;

        let id = if !xtd {
            can::Id::Standard((r0.read(RX_ELEMENT_R0::ID) >> 18) as u16)
        } else {
            can::Id::Extended(r0.read(RX_ELEMENT_R0::ID))
        };

        self.rx_buffer.map(|rx| {
            for i in 0..2 {
                let word = element.data[i].get();
                rx[i * 4] = (word & 0xFF) as u8;
                rx[i * 4 + 1] = ((word >> 8) & 0xFF) as u8;
                rx[i * 4 + 2] = ((word >> 16) & 0xFF) as u8;
                rx[i * 4 + 3] = ((word >> 24) & 0xFF) as u8;
            }
        });

        self.registers.fdcan_rxf0a.set(get_index as u32);
        self.receive_client.map(|client| {
            self.rx_buffer.take().map(|buf| {
                client.message_received(id, buf, dlc, Ok(()));
            });
        });
    }
}

impl DeferredCallClient for Can {
    fn register(&'static self) {
        self.deferred_call.register(self);
    }
    fn handle_deferred_call(&self) {
        match self.deferred_action.take() {
            Some(action) => match action {
                AsyncAction::Enable => {
                    if let Err(enable_err) = self.enter_normal_mode() {
                        self.controller_client.map(|controller_client| {
                            controller_client.state_changed(self.can_state.get().into());
                            controller_client.enabled(Err(enable_err));
                        });
                    }
                    self.controller_client.map(|controller_client| {
                        controller_client.state_changed(can::State::Running);
                        controller_client.enabled(Ok(()));
                    });
                }
                AsyncAction::AbortReceive => {
                    if let Some(rx) = self.rx_buffer.take() {
                        self.receive_client
                            .map(|receive_client| receive_client.stopped(rx));
                    }
                }
                AsyncAction::Disabled => {
                    self.controller_client.map(|controller_client| {
                        controller_client.state_changed(self.can_state.get().into());
                        controller_client.disabled(Ok(()));
                    });
                }
                AsyncAction::EnableError(err) => {
                    self.controller_client.map(|controller_client| {
                        controller_client.state_changed(self.can_state.get().into());
                        controller_client.enabled(Err(err));
                    });
                }
            },
            None => todo!(),
        }
    }
}

impl can::Configure for Can {
    const MIN_BIT_TIMINGS: can::BitTiming = can::BitTiming {
        segment1: BitSegment1::CanBtrTs1Min as u8,
        segment2: BitSegment2::CanBtrTs2Min as u8,
        propagation: 0,
        sync_jump_width: SynchronizationJumpWidth::CanBtrSjwMin as u32,
        baud_rate_prescaler: NBRP_MIN,
    };

    const MAX_BIT_TIMINGS: can::BitTiming = can::BitTiming {
        segment1: BitSegment1::CanBtrTs1Max as u8,
        segment2: BitSegment2::CanBtrTs2Max as u8,
        propagation: 0,
        sync_jump_width: SynchronizationJumpWidth::CanBtrSjwMax as u32,
        baud_rate_prescaler: NBRP_MAX,
    };

    const SYNC_SEG: u8 = 1;

    fn set_bitrate(&self, bitrate: u32) -> Result<(), kernel::ErrorCode> {
        let bit_timing = Self::bit_timing_for_bitrate(16_000_000, bitrate)?;
        self.set_bit_timing(bit_timing)
    }

    fn set_bit_timing(&self, bit_timing: can::BitTiming) -> Result<(), kernel::ErrorCode> {
        match self.can_state.get() {
            CanState::Sleep => {
                self.bit_timing.set(bit_timing);
                Ok(())
            }
            CanState::Normal | CanState::Initialization | CanState::RunningError(_) => {
                Err(kernel::ErrorCode::BUSY)
            }
        }
    }

    fn set_operation_mode(&self, mode: can::OperationMode) -> Result<(), kernel::ErrorCode> {
        match self.can_state.get() {
            CanState::Sleep => {
                self.operating_mode.set(mode);
                Ok(())
            }
            CanState::Normal | CanState::Initialization | CanState::RunningError(_) => {
                Err(kernel::ErrorCode::BUSY)
            }
        }
    }

    fn get_bit_timing(&self) -> Result<can::BitTiming, kernel::ErrorCode> {
        if let Some(bit_timing) = self.bit_timing.get() {
            Ok(bit_timing)
        } else {
            Err(kernel::ErrorCode::INVAL)
        }
    }

    fn get_operation_mode(&self) -> Result<can::OperationMode, kernel::ErrorCode> {
        if let Some(operation_mode) = self.operating_mode.get() {
            Ok(operation_mode)
        } else {
            Err(kernel::ErrorCode::INVAL)
        }
    }

    fn set_automatic_retransmission(&self, automatic: bool) -> Result<(), kernel::ErrorCode> {
        match self.can_state.get() {
            CanState::Sleep => {
                self.automatic_retransmission.replace(automatic);
                Ok(())
            }
            CanState::Normal | CanState::Initialization | CanState::RunningError(_) => {
                Err(kernel::ErrorCode::BUSY)
            }
        }
    }

    fn set_wake_up(&self, wake_up: bool) -> Result<(), kernel::ErrorCode> {
        Err(kernel::ErrorCode::NOSUPPORT)
    }

    fn get_automatic_retransmission(&self) -> Result<bool, kernel::ErrorCode> {
        Ok(self.automatic_retransmission.get())
    }

    fn get_wake_up(&self) -> Result<bool, kernel::ErrorCode> {
        Err(kernel::ErrorCode::NOSUPPORT)
    }

    fn receive_fifo_count(&self) -> usize {
        2
    }
}

impl can::Controller for Can {
    fn set_client(&self, client: Option<&'static dyn can::ControllerClient>) {
        if let Some(client) = client {
            self.controller_client.replace(client);
        } else {
            self.controller_client.clear();
        }
    }
    fn enable(&self) -> Result<(), kernel::ErrorCode> {
        match self.can_state.get() {
            CanState::Sleep => {
                if self.bit_timing.is_none() || self.operating_mode.is_none() {
                    Err(kernel::ErrorCode::INVAL)
                } else {
                    let r = self.enable();
                    // there is another deferred action that must be completed
                    if self.deferred_action.is_some() {
                        Err(kernel::ErrorCode::BUSY)
                    } else {
                        // set an Enable or an EnableError deferred action
                        match r {
                            Ok(()) => {
                                self.deferred_action.set(AsyncAction::Enable);
                            }
                            Err(err) => {
                                self.deferred_action.set(AsyncAction::EnableError(err));
                            }
                        }
                        self.deferred_call.set();
                        r
                    }
                }
            }
            CanState::Normal | CanState::Initialization => Err(kernel::ErrorCode::ALREADY),
            CanState::RunningError(_) => Err(kernel::ErrorCode::FAIL),
        }
    }

    fn disable(&self) -> Result<(), kernel::ErrorCode> {
        match self.can_state.get() {
            CanState::Normal | CanState::RunningError(_) => {
                self.disable();
                if self.deferred_action.is_some() {
                    // there is another deferred action that must be completed
                    return Err(kernel::ErrorCode::BUSY);
                } else {
                    // set a Disable deferred action
                    self.deferred_action.set(AsyncAction::Disabled);
                    self.deferred_call.set();
                }
                Ok(())
            }
            CanState::Sleep | CanState::Initialization => Err(kernel::ErrorCode::OFF),
        }
    }

    fn get_state(&self) -> Result<can::State, kernel::ErrorCode> {
        Ok(self.can_state.get().into())
    }
}

impl can::Transmit<{ can::STANDARD_CAN_PACKET_SIZE }> for Can {
    fn set_client(
        &self,
        client: Option<&'static dyn can::TransmitClient<{ can::STANDARD_CAN_PACKET_SIZE }>>,
    ) {
        if let Some(client) = client {
            self.transmit_client.set(client);
        } else {
            self.transmit_client.clear();
        }
    }

    fn send(
        &self,
        id: can::Id,
        buffer: &'static mut [u8; can::STANDARD_CAN_PACKET_SIZE],
        len: usize,
    ) -> Result<
        (),
        (
            kernel::ErrorCode,
            &'static mut [u8; can::STANDARD_CAN_PACKET_SIZE],
        ),
    > {
        match self.can_state.get() {
            CanState::Normal | CanState::RunningError(_) => {
                self.tx_buffer.replace(buffer);
                self.enable_irq(CanInterruptMode::TransmitInterrupt);
                self.can_state.set(CanState::Normal);
                match self.send_8byte_message(id, len, 0) {
                    Ok(()) => Ok(()),
                    Err(err) => Err((err, self.tx_buffer.take().unwrap())),
                }
            }
            CanState::Sleep | CanState::Initialization => Err((kernel::ErrorCode::OFF, buffer)),
        }
    }
}

impl can::Receive<{ can::STANDARD_CAN_PACKET_SIZE }> for Can {
    fn set_client(
        &self,
        client: Option<&'static dyn can::ReceiveClient<{ can::STANDARD_CAN_PACKET_SIZE }>>,
    ) {
        if let Some(client) = client {
            self.receive_client.set(client);
        } else {
            self.receive_client.clear();
        }
    }

    fn start_receive_process(
        &self,
        buffer: &'static mut [u8; can::STANDARD_CAN_PACKET_SIZE],
    ) -> Result<
        (),
        (
            kernel::ErrorCode,
            &'static mut [u8; can::STANDARD_CAN_PACKET_SIZE],
        ),
    > {
        match self.can_state.get() {
            CanState::Normal | CanState::RunningError(_) => {
                self.can_state.set(CanState::Normal);
                self.config_filter(
                    can::FilterParameters {
                        number: 0,
                        scale_bits: can::ScaleBits::Bits32,
                        identifier_mode: can::IdentifierMode::Mask,
                        fifo_number: 0,
                    },
                    true,
                );
                self.config_filter(
                    can::FilterParameters {
                        number: 1,
                        scale_bits: can::ScaleBits::Bits32,
                        identifier_mode: can::IdentifierMode::Mask,
                        fifo_number: 1,
                    },
                    true,
                );
                self.enable_filter_config();
                self.enable_irq(CanInterruptMode::Fifo0Interrupt);
                self.enable_irq(CanInterruptMode::Fifo1Interrupt);
                self.rx_buffer.put(Some(buffer));
                Ok(())
            }
            CanState::Sleep | CanState::Initialization => Err((kernel::ErrorCode::OFF, buffer)),
        }
    }

    fn stop_receive(&self) -> Result<(), kernel::ErrorCode> {
        match self.can_state.get() {
            CanState::Normal | CanState::RunningError(_) => {
                self.can_state.set(CanState::Normal);
                self.config_filter(
                    can::FilterParameters {
                        number: 0,
                        scale_bits: can::ScaleBits::Bits32,
                        identifier_mode: can::IdentifierMode::Mask,
                        fifo_number: 0,
                    },
                    false,
                );
                self.config_filter(
                    can::FilterParameters {
                        number: 1,
                        scale_bits: can::ScaleBits::Bits32,
                        identifier_mode: can::IdentifierMode::Mask,
                        fifo_number: 1,
                    },
                    false,
                );
                self.enable_filter_config();
                self.disable_irq(CanInterruptMode::Fifo0Interrupt);
                self.disable_irq(CanInterruptMode::Fifo1Interrupt);
                // there is another deferred action that must be completed
                if self.deferred_action.is_some() {
                    Err(kernel::ErrorCode::BUSY)
                // the chip does not own the buffer from the capsule
                } else if self.rx_buffer.is_none() {
                    Err(kernel::ErrorCode::SIZE)
                } else {
                    // set a AbortReceive deferred action
                    self.deferred_action.set(AsyncAction::AbortReceive);
                    self.deferred_call.set();
                    Ok(())
                }
            }
            CanState::Sleep | CanState::Initialization => Err(kernel::ErrorCode::OFF),
        }
    }
}

register_structs! {
    RxElement {                                   // 18 words
        (0x00 => r0: ReadWrite<u32, RX_ELEMENT_R0::Register>),   // ID + XTD/RTR/ESI
        (0x04 => r1: ReadWrite<u32, RX_ELEMENT_R1::Register>),   // DLC + flags + timestamp
        (0x08 => data: [ReadWrite<u32>; 16]),                    // 64 B; classic uses data[0..2]
        (0x48 => @END),
    }
}
register_structs! {
    TxElement {                                   // 18 words
        (0x00 => t0: ReadWrite<u32, TX_ELEMENT_T0::Register>),
        (0x04 => t1: ReadWrite<u32, TX_ELEMENT_T1::Register>),
        (0x08 => data: [ReadWrite<u32>; 16]),
        (0x48 => @END),
    }
}
register_structs! {
    TxEventElement {                              // 2 words
        (0x00 => e0: ReadWrite<u32>),
        (0x04 => e1: ReadWrite<u32>),
        (0x08 => @END),
    }
}
register_structs! {
    ExtFilter {                                   // 2 words
        (0x00 => f0: ReadWrite<u32, EXT_FILTER_F0::Register>),
        (0x04 => f1: ReadWrite<u32, EXT_FILTER_F1::Register>),
        (0x08 => @END),
    }
}
register_structs! {
    pub Fdcan1MessageRam {
        (0x0000 => std_filters: [ReadWrite<u32, STD_FILTER::Register>; 28]),  // 28 w
        (0x0070 => ext_filters: [ExtFilter; 8]),        // 8 × 2  = 16 w
        (0x00B0 => rx_fifo0:    [RxElement; 3]),        // 3 × 18 = 54 w
        (0x0188 => rx_fifo1:    [RxElement; 3]),        // 3 × 18 = 54 w
        (0x0260 => tx_event:    [TxEventElement; 3]),   // 3 × 2  = 6 w
        (0x0278 => tx_buffers:  [TxElement; 3]),        // 3 × 18 = 54 w
        (0x0350 => @END),
    }
}

//message ram structure as its easiest to work with it with tock registers
register_bitfields![u32,
    STD_FILTER [
        SFID2 OFFSET(0)  NUMBITS(11) [],
        SFID1 OFFSET(16) NUMBITS(11) [],
        SFEC  OFFSET(27) NUMBITS(3) [
            DISABLE = 0, FIFO0 = 1, FIFO1 = 2, REJECT = 3,
            PRIORITY = 4, PRIORITY_FIFO0 = 5, PRIORITY_FIFO1 = 6,
        ],
        SFT   OFFSET(30) NUMBITS(2) [
            RANGE = 0, DUAL = 1, CLASSIC = 2, DISABLED = 3,
        ],
    ],

    EXT_FILTER_F0 [
        EFID1 OFFSET(0)  NUMBITS(29) [],
        EFEC  OFFSET(29) NUMBITS(3) [
            DISABLE = 0, FIFO0 = 1, FIFO1 = 2, REJECT = 3,
            PRIORITY = 4, PRIORITY_FIFO0 = 5, PRIORITY_FIFO1 = 6,
        ],
    ],
    EXT_FILTER_F1 [
        EFID2 OFFSET(0)  NUMBITS(29) [],
        EFT   OFFSET(30) NUMBITS(2) [
            RANGE = 0, DUAL = 1, CLASSIC = 2, RANGE_NO_XIDAM = 3,
        ],
    ],

    RX_ELEMENT_R0 [
        ID  OFFSET(0)  NUMBITS(29) [],
        RTR OFFSET(29) NUMBITS(1)  [],
        XTD OFFSET(30) NUMBITS(1)  [],   // 0 = standard, 1 = extended
        ESI OFFSET(31) NUMBITS(1)  [],
    ],
    RX_ELEMENT_R1 [
        RXTS OFFSET(0)  NUMBITS(16) [],  // rx timestamp
        DLC  OFFSET(16) NUMBITS(4)  [],
        BRS  OFFSET(20) NUMBITS(1)  [],
        FDF  OFFSET(21) NUMBITS(1)  [],
        FIDX OFFSET(24) NUMBITS(7)  [],  // matching filter index
        ANMF OFFSET(31) NUMBITS(1)  [],  // accepted non-matching frame
    ],
    TX_ELEMENT_T0 [
        ID  OFFSET(0)  NUMBITS(29) [],
        RTR OFFSET(29) NUMBITS(1)  [],
        XTD OFFSET(30) NUMBITS(1)  [],
        ESI OFFSET(31) NUMBITS(1)  [],
    ],
    TX_ELEMENT_T1 [
        DLC OFFSET(16) NUMBITS(4) [],
        BRS OFFSET(20) NUMBITS(1) [],
        FDF OFFSET(21) NUMBITS(1) [],
        EFC OFFSET(23) NUMBITS(1) [],    // 1 = store a Tx event FIFO entry
        MM  OFFSET(24) NUMBITS(8) [],    // message marker (echoed in the event)
    ],
];
