////////////////////////////////////////////////////////////////////////////////
// Autogenerated by svd2regs.py on 2026-07-06
//   svd2regs.py --svd STM32U545.svd --save fdcan.rs --group FDCAN

use kernel::utilities::registers::{
    self, register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly,
};
use kernel::utilities::StaticRef;

use core::cell::Cell;
use kernel::deferred_call::{DeferredCall, DeferredCallClient};
use kernel::hil::can::{self, StandardBitTiming};
use kernel::platform::chip::ClockInterface;
use kernel::utilities::cells::{OptionalCell, TakeCell};
use kernel::utilities::registers::interfaces::{ReadWriteable, Readable};
use kernel::utilities::StaticRef;


register_structs! {
    /// FDCAN1_RAM
    FdcanRegisters {
        /// FDCAN Core Release Register
        (0x000 => fdcan_crel: ReadOnly<u32, FDCAN_CREL::Register>),
        /// FDCAN endian register
        (0x004 => fdcan_endn: ReadOnly<u32>),
        (0x008 => _reserved0),
        /// FDCAN Data Bit Timing and Prescaler
        (0x00C => fdcan_dbtp: ReadWrite<u32, FDCAN_DBTP::Register>),
        /// FDCAN Test Register
        (0x010 => fdcan_test: ReadWrite<u32, FDCAN_TEST::Register>),
        /// FDCAN RAM Watchdog Register
        (0x014 => fdcan_rwd: ReadWrite<u32, FDCAN_RWD::Register>),
        /// FDCAN CC Control Register
        (0x018 => fdcan_cccr: ReadWrite<u32, FDCAN_CCCR::Register>),
        /// FDCAN Nominal Bit Timing and Prescaler
        (0x01C => fdcan_nbtp: ReadWrite<u32, FDCAN_NBTP::Register>),
        /// FDCAN Timestamp Counter Configuration
        (0x020 => fdcan_tscc: ReadWrite<u32, FDCAN_TSCC::Register>),
        /// FDCAN Timestamp Counter Value
        (0x024 => fdcan_tscv: ReadWrite<u32>),
        /// FDCAN Timeout Counter Configuration
        (0x028 => fdcan_tocc: ReadWrite<u32, FDCAN_TOCC::Register>),
        /// FDCAN Timeout Counter Value
        (0x02C => fdcan_tocv: ReadWrite<u32>),
        (0x030 => _reserved1),
        /// FDCAN Error Counter Register
        (0x040 => fdcan_ecr: ReadWrite<u32, FDCAN_ECR::Register>),
        /// FDCAN Protocol Status Register
        (0x044 => fdcan_psr: ReadWrite<u32, FDCAN_PSR::Register>),
        /// FDCAN Transmitter Delay Compensation
        (0x048 => fdcan_tdcr: ReadWrite<u32, FDCAN_TDCR::Register>),
        (0x04C => _reserved2),
        /// FDCAN Interrupt Register
        (0x050 => fdcan_ir: ReadWrite<u32, FDCAN_IR::Register>),
        /// FDCAN Interrupt Enable
        (0x054 => fdcan_ie: ReadWrite<u32, FDCAN_IE::Register>),
        /// FDCAN Interrupt Line Select
        (0x058 => fdcan_ils: ReadWrite<u32, FDCAN_ILS::Register>),
        /// FDCAN Interrupt Line Enable
        (0x05C => fdcan_ile: ReadWrite<u32, FDCAN_ILE::Register>),
        (0x060 => _reserved3),
        /// FDCAN Global Filter Configuration
        (0x080 => fdcan_rxgfc: ReadWrite<u32, FDCAN_RXGFC::Register>),
        /// FDCAN Extended ID and Mask
        (0x084 => fdcan_xidam: ReadWrite<u32>),
        /// FDCAN High Priority Message Status
        (0x088 => fdcan_hpms: ReadOnly<u32, FDCAN_HPMS::Register>),
        (0x08C => _reserved4),
        /// FDCAN Rx FIFO 0 Status
        (0x090 => fdcan_rxf0s: ReadOnly<u32, FDCAN_RXF0S::Register>),
        /// CAN Rx FIFO 0 Acknowledge
        (0x094 => fdcan_rxf0a: ReadWrite<u32>),
        /// FDCAN Rx FIFO 1 Status
        (0x098 => fdcan_rxf1s: ReadOnly<u32, FDCAN_RXF1S::Register>),
        /// FDCAN Rx FIFO 1 Acknowledge
        (0x09C => fdcan_rxf1a: ReadWrite<u32>),
        (0x0A0 => _reserved5),
        /// FDCAN Tx buffer configuration register
        (0x0C0 => fdcan_txbc: ReadWrite<u32>),
        /// FDCAN Tx FIFO/Queue Status
        (0x0C4 => fdcan_txfqs: ReadOnly<u32, FDCAN_TXFQS::Register>),
        /// FDCAN Tx Buffer Request Pending
        (0x0C8 => fdcan_txbrp: ReadOnly<u32>),
        /// FDCAN Tx Buffer Add Request
        (0x0CC => fdcan_txbar: ReadWrite<u32>),
        /// FDCAN Tx Buffer Cancellation Request
        (0x0D0 => fdcan_txbcr: ReadWrite<u32>),
        /// FDCAN Tx Buffer Transmission Occurred
        (0x0D4 => fdcan_txbto: ReadOnly<u32>),
        /// FDCAN Tx Buffer Cancellation Finished
        (0x0D8 => fdcan_txbcf: ReadOnly<u32>),
        /// FDCAN Tx Buffer Transmission Interrupt
        (0x0DC => fdcan_txbtie: ReadWrite<u32>),
        /// FDCAN Tx Buffer Cancellation Finished
        (0x0E0 => fdcan_txbcie: ReadWrite<u32>),
        /// FDCAN Tx Event FIFO Status
        (0x0E4 => fdcan_txefs: ReadOnly<u32, FDCAN_TXEFS::Register>),
        /// FDCAN Tx Event FIFO Acknowledge
        (0x0E8 => fdcan_txefa: ReadWrite<u32>),
        (0x0EC => _reserved6),
        /// FDCAN CFG clock divider register
        (0x100 => fdcan_ckdiv: ReadWrite<u32>),
        (0x104 => @END),
    }
}
register_bitfields![u32,
FDCAN_CREL [
    /// Core release
    REL OFFSET(28) NUMBITS(4) [],
    /// Step of Core release
    STEP OFFSET(24) NUMBITS(4) [],
    /// Sub-step of Core release
    SUBSTEP OFFSET(20) NUMBITS(4) [],
    /// Timestamp Year
    YEAR OFFSET(16) NUMBITS(4) [],
    /// Timestamp Month
    MON OFFSET(8) NUMBITS(8) [],
    /// Timestamp Day
    DAY OFFSET(0) NUMBITS(8) []
],
FDCAN_ENDN [
    /// Endiannes Test Value
    ETV OFFSET(0) NUMBITS(32) []
],
FDCAN_DBTP [
    /// Synchronization Jump Width
    DSJW OFFSET(0) NUMBITS(4) [],
    /// Data time segment after sample
    DTSEG2 OFFSET(4) NUMBITS(4) [],
    /// Data time segment after sample
    DTSEG1 OFFSET(8) NUMBITS(5) [],
    /// Data BIt Rate Prescaler
    DBRP OFFSET(16) NUMBITS(5) [],
    /// Transceiver Delay
    TDC OFFSET(23) NUMBITS(1) []
],
FDCAN_TEST [
    /// Loop Back mode
    LBCK OFFSET(4) NUMBITS(1) [],
    // TX Pin control
    TX OFFSET(5) NUMBITS(2) [
        CAN_CORE = 0,
        SP = 1,
        DOMINANT = 2,
        RECESSIVE = 3,
    ],
    /// Control of Transmit Pin
    RX OFFSET(7) NUMBITS(1) []
],
FDCAN_RWD [
    /// Watchdog value
    WDV OFFSET(8) NUMBITS(8) [],
    /// Watchdog configuration
    WDC OFFSET(0) NUMBITS(8) []
],
FDCAN_CCCR [
    /// Initialization
    INIT OFFSET(0) NUMBITS(1) [],
    /// Configuration Change
    CCE OFFSET(1) NUMBITS(1) [],
    /// ASM Restricted Operation
    ASM OFFSET(2) NUMBITS(1) [],
    /// Clock Stop Acknowledge
    CSA OFFSET(3) NUMBITS(1) [],
    /// Clock Stop Request
    CSR OFFSET(4) NUMBITS(1) [],
    /// Bus Monitoring Mode
    MON OFFSET(5) NUMBITS(1) [],
    /// Disable Automatic
    DAR OFFSET(6) NUMBITS(1) [],
    /// Test Mode Enable
    TEST OFFSET(7) NUMBITS(1) [],
    /// FD Operation Enable
    FDOE OFFSET(8) NUMBITS(1) [],
    /// FDCAN Bit Rate Switching
    BRSE OFFSET(9) NUMBITS(1) [],
    /// Protocol Exception Handling
    PXHD OFFSET(12) NUMBITS(1) [],
    /// Edge Filtering during Bus
    EFBI OFFSET(13) NUMBITS(1) [],
    /// TXP
    TXP OFFSET(14) NUMBITS(1) [],
    /// Non ISO Operation
    NISO OFFSET(15) NUMBITS(1) []
],
FDCAN_NBTP [
    /// Nominal (Re)Synchronization Jump
    NSJW OFFSET(25) NUMBITS(7) [],
    /// Bit Rate Prescaler
    NBRP OFFSET(16) NUMBITS(9) [],
    /// Nominal Time segment before sample
    NTSEG1 OFFSET(8) NUMBITS(8) [],
    /// Nominal Time segment after sample
    NTSEG2 OFFSET(0) NUMBITS(7) []
],
FDCAN_TSCC [
    /// Timestamp Counter
    TCP OFFSET(16) NUMBITS(4) [],
    /// Timestamp Select
    TSS OFFSET(0) NUMBITS(2) []
],
FDCAN_TSCV [
    /// Timestamp Counter
    TSC OFFSET(0) NUMBITS(16) []
],
FDCAN_TOCC [
    /// Enable Timeout Counter
    ETOC OFFSET(0) NUMBITS(1) [],
    /// Timeout Select
    TOS OFFSET(1) NUMBITS(2) [],
    /// Timeout Period
    TOP OFFSET(16) NUMBITS(16) []
],
FDCAN_TOCV [
    /// Timeout Counter
    TOC OFFSET(0) NUMBITS(16) []
],
FDCAN_ECR [
    /// AN Error Logging
    CEL OFFSET(16) NUMBITS(8) [],
    /// Receive Error Passive
    RP OFFSET(15) NUMBITS(1) [],
    /// Receive Error Counter
    REC OFFSET(8) NUMBITS(7) [],
    /// Transmit Error Counter
    TEC OFFSET(0) NUMBITS(8) []
],
FDCAN_PSR [
    /// Last Error Code
    LEC OFFSET(0) NUMBITS(3) [],
    /// Activity
    ACT OFFSET(3) NUMBITS(2) [],
    /// Error Passive
    EP OFFSET(5) NUMBITS(1) [],
    /// Warning Status
    EW OFFSET(6) NUMBITS(1) [],
    /// Bus_Off Status
    BO OFFSET(7) NUMBITS(1) [],
    /// Data Last Error Code
    DLEC OFFSET(8) NUMBITS(3) [],
    /// ESI flag of last received FDCAN
    RESI OFFSET(11) NUMBITS(1) [],
    /// BRS flag of last received FDCAN
    RBRS OFFSET(12) NUMBITS(1) [],
    /// Received FDCAN Message
    REDL OFFSET(13) NUMBITS(1) [],
    /// Protocol Exception Event
    PXE OFFSET(14) NUMBITS(1) [],
    /// Transmitter Delay Compensation
    TDCV OFFSET(16) NUMBITS(7) []
],
FDCAN_TDCR [
    /// Transmitter Delay Compensation Filter
    TDCF OFFSET(0) NUMBITS(7) [],
    /// Transmitter Delay Compensation
    TDCO OFFSET(8) NUMBITS(7) []
],
FDCAN_IR [
    /// RF0N
    RF0N OFFSET(0) NUMBITS(1) [],
    /// RF0F
    RF0F OFFSET(1) NUMBITS(1) [],
    /// RF0L
    RF0L OFFSET(2) NUMBITS(1) [],
    /// RF1N
    RF1N OFFSET(3) NUMBITS(1) [],
    /// RF1F
    RF1F OFFSET(4) NUMBITS(1) [],
    /// RF1L
    RF1L OFFSET(5) NUMBITS(1) [],
    /// HPM
    HPM OFFSET(6) NUMBITS(1) [],
    /// TC
    TC OFFSET(7) NUMBITS(1) [],
    /// TCF
    TCF OFFSET(8) NUMBITS(1) [],
    /// TFE
    TFE OFFSET(9) NUMBITS(1) [],
    /// TEFN
    TEFN OFFSET(10) NUMBITS(1) [],
    /// TEFF
    TEFF OFFSET(11) NUMBITS(1) [],
    /// TEFL
    TEFL OFFSET(12) NUMBITS(1) [],
    /// TSW
    TSW OFFSET(13) NUMBITS(1) [],
    /// MRAF
    MRAF OFFSET(14) NUMBITS(1) [],
    /// TOO
    TOO OFFSET(15) NUMBITS(1) [],
    /// ELO
    ELO OFFSET(16) NUMBITS(1) [],
    /// EP
    EP OFFSET(17) NUMBITS(1) [],
    /// EW
    EW OFFSET(18) NUMBITS(1) [],
    /// BO
    BO OFFSET(19) NUMBITS(1) [],
    /// WDI
    WDI OFFSET(20) NUMBITS(1) [],
    /// PEA
    PEA OFFSET(21) NUMBITS(1) [],
    /// PED
    PED OFFSET(22) NUMBITS(1) [],
    /// ARA
    ARA OFFSET(23) NUMBITS(1) []
],
FDCAN_IE [
    /// Rx FIFO 0 New Message
    RF0NE OFFSET(0) NUMBITS(1) [],
    /// Rx FIFO 0 Full Enable
    RF0FE OFFSET(1) NUMBITS(1) [],
    /// Rx FIFO 0 Message Lost
    RF0LE OFFSET(2) NUMBITS(1) [],
    /// Rx FIFO 1 New Message
    RF1NE OFFSET(3) NUMBITS(1) [],
    /// Rx FIFO 1 Watermark Reached
    RF1FE OFFSET(4) NUMBITS(1) [],
    /// Rx FIFO 1 Message Lost
    RF1LE OFFSET(5) NUMBITS(1) [],
    /// High Priority Message
    HPME OFFSET(6) NUMBITS(1) [],
    /// Transmission Completed
    TCE OFFSET(7) NUMBITS(1) [],
    /// Transmission Cancellation Finished
    TCFE OFFSET(8) NUMBITS(1) [],
    /// Tx FIFO Empty Enable
    TEFE OFFSET(9) NUMBITS(1) [],
    /// Tx Event FIFO New Entry
    TEFNE OFFSET(10) NUMBITS(1) [],
    /// Tx Event FIFO Full Enable
    TEFFE OFFSET(11) NUMBITS(1) [],
    /// Tx Event FIFO Element Lost
    TEFLE OFFSET(12) NUMBITS(1) [],
    /// TSWE
    TSWE OFFSET(13) NUMBITS(1) [],
    /// Message RAM Access Failure
    MRAFE OFFSET(14) NUMBITS(1) [],
    /// Timeout Occurred Enable
    TOOE OFFSET(15) NUMBITS(1) [],
    /// Error Logging Overflow
    ELOE OFFSET(16) NUMBITS(1) [],
    /// Error Passive Enable
    EPE OFFSET(17) NUMBITS(1) [],
    /// Warning Status Enable
    EWE OFFSET(18) NUMBITS(1) [],
    /// Bus_Off Status Enable
    BOE OFFSET(19) NUMBITS(1) [],
    /// Watchdog Interrupt Enable
    WDIE OFFSET(20) NUMBITS(1) [],
    /// Protocol Error in Arbitration Phase
    PEAE OFFSET(21) NUMBITS(1) [],
    /// Protocol Error in Data Phase
    PEDE OFFSET(22) NUMBITS(1) [],
    /// Access to Reserved Address
    ARAE OFFSET(23) NUMBITS(1) []
],
FDCAN_ILS [
    /// RxFIFO0
    RxFIFO0 OFFSET(0) NUMBITS(1) [],
    /// RxFIFO1
    RxFIFO1 OFFSET(1) NUMBITS(1) [],
    /// SMSG
    SMSG OFFSET(2) NUMBITS(1) [],
    /// TFERR
    TFERR OFFSET(3) NUMBITS(1) [],
    /// MISC
    MISC OFFSET(4) NUMBITS(1) [],
    /// BERR
    BERR OFFSET(5) NUMBITS(1) [],
    /// PERR
    PERR OFFSET(6) NUMBITS(1) []
],
FDCAN_ILE [
    /// Enable Interrupt Line 0
    EINT0 OFFSET(0) NUMBITS(1) [],
    /// Enable Interrupt Line 1
    EINT1 OFFSET(1) NUMBITS(1) []
],
FDCAN_RXGFC [
    /// Reject Remote Frames
    RRFE OFFSET(0) NUMBITS(1) [],
    /// Reject Remote Frames
    RRFS OFFSET(1) NUMBITS(1) [],
    /// Accept Non-matching Frames
    ANFE OFFSET(2) NUMBITS(2) [],
    /// Accept Non-matching Frames
    ANFS OFFSET(4) NUMBITS(2) [],
    /// F1OM
    F1OM OFFSET(8) NUMBITS(1) [],
    /// F0OM
    F0OM OFFSET(9) NUMBITS(1) [],
    /// LSS
    LSS OFFSET(16) NUMBITS(5) [],
    /// LSE
    LSE OFFSET(24) NUMBITS(4) []
],
FDCAN_XIDAM [
    /// Extended ID Mask
    EIDM OFFSET(0) NUMBITS(29) []
],
FDCAN_HPMS [
    /// Buffer Index
    BIDX OFFSET(0) NUMBITS(3) [],
    /// Message Storage Indicator
    MSI OFFSET(6) NUMBITS(2) [],
    /// Filter Index
    FIDX OFFSET(8) NUMBITS(5) [],
    /// Filter List
    FLST OFFSET(15) NUMBITS(1) []
],
FDCAN_RXF0S [
    /// Rx FIFO 0 Fill Level
    F0FL OFFSET(0) NUMBITS(4) [],
    /// Rx FIFO 0 Get Index
    F0GI OFFSET(8) NUMBITS(2) [],
    /// Rx FIFO 0 Put Index
    F0PI OFFSET(16) NUMBITS(2) [],
    /// Rx FIFO 0 Full
    F0F OFFSET(24) NUMBITS(1) [],
    /// Rx FIFO 0 Message Lost
    RF0L OFFSET(25) NUMBITS(1) []
],
FDCAN_RXF0A [
    /// Rx FIFO 0 Acknowledge
    F0AI OFFSET(0) NUMBITS(3) []
],
FDCAN_RXF1S [
    /// Rx FIFO 1 Fill Level
    F1FL OFFSET(0) NUMBITS(4) [],
    /// Rx FIFO 1 Get Index
    F1GI OFFSET(8) NUMBITS(2) [],
    /// Rx FIFO 1 Put Index
    F1PI OFFSET(16) NUMBITS(2) [],
    /// Rx FIFO 1 Full
    F1F OFFSET(24) NUMBITS(1) [],
    /// Rx FIFO 1 Message Lost
    RF1L OFFSET(25) NUMBITS(1) []
],
FDCAN_RXF1A [
    /// Rx FIFO 1 Acknowledge
    F1AI OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBC [
    /// Tx FIFO/Queue Mode
    TFQM OFFSET(24) NUMBITS(1) []
],
FDCAN_TXFQS [
    /// Tx FIFO Free Level
    TFFL OFFSET(0) NUMBITS(3) [],
    /// TFGI
    TFGI OFFSET(8) NUMBITS(2) [],
    /// Tx FIFO/Queue Put Index
    TFQPI OFFSET(16) NUMBITS(2) [],
    /// Tx FIFO/Queue Full
    TFQF OFFSET(21) NUMBITS(1) []
],
FDCAN_TXBRP [
    /// Transmission Request
    TRP OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBAR [
    /// Add Request
    AR OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBCR [
    /// Cancellation Request
    CR OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBTO [
    /// Transmission Occurred.
    TO OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBCF [
    /// Cancellation Finished
    CF OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBTIE [
    /// Transmission Interrupt
    TIE OFFSET(0) NUMBITS(3) []
],
FDCAN_TXBCIE [
    /// Cancellation Finished Interrupt
    CFIE OFFSET(0) NUMBITS(3) []
],
FDCAN_TXEFS [
    /// Event FIFO Fill Level
    EFFL OFFSET(0) NUMBITS(3) [],
    /// Event FIFO Get Index.
    EFGI OFFSET(8) NUMBITS(2) [],
    /// Event FIFO Put Index
    EFPI OFFSET(16) NUMBITS(2) [],
    /// Event FIFO Full.
    EFF OFFSET(24) NUMBITS(1) [],
    /// Tx Event FIFO Element
    TEFL OFFSET(25) NUMBITS(1) []
],
FDCAN_TXEFA [
    /// Event FIFO Acknowledge
    EFAI OFFSET(0) NUMBITS(2) []
],
FDCAN_CKDIV [
    /// PDIV
    PDIV OFFSET(0) NUMBITS(4) []
]
];
const FDCAN1_RAM_BASE: StaticRef<FdcanRegisters> =
    unsafe { StaticRef::new(0x4000AC00 as *const FdcanRegisters) };

const SEC_FDCAN1_RAM_BASE: StaticRef<FdcanRegisters> =
    unsafe { StaticRef::new(0x5000AC00 as *const FdcanRegisters) };

const FDCAN1_BASE: StaticRef<FdcanRegisters> =
    unsafe { StaticRef::new(0x4000A400 as *const FdcanRegisters) };

const SEC_FDCAN1_BASE: StaticRef<FdcanRegisters> =
    unsafe { StaticRef::new(0x5000A400 as *const FdcanRegisters) };

// End autogenerated block
////////////////////////////////////////////////////////////////////////////////

type Registers = FdcanRegisters;


#[derive(Copy, Clone, PartialEq)]
enum CanState {
    Initialization,
    Normal,
    Sleep,
    RunningError(can::Error),
}

#[derive(Copy, Clone, PartialEq)]
enum AsyncAction {
    Enable,
    AbortReceive,
    Disabled,
    EnableError(kernel::ErrorCode),
}


#[repr(u32)]
enum BitSegment1 {
    CanBtrTs1Min = 0b0000,
    CanBtrTs1Max = 0b1111,
}

#[repr(u32)]
enum BitSegment2 {
    CanBtrTs2Min = 0b0000,
    CanBtrTs2Max = 0b0111,
}

#[repr(u32)]
enum SynchronizationJumpWidth {
    CanBtrSjwMin = 0b00,
    CanBtrSjwMax = 0b11,
}

#[derive(Copy, Clone, PartialEq)]
pub enum CanInterruptMode {
    TransmitInterrupt,
    Fifo0Interrupt,
    Fifo1Interrupt,
    ErrorAndStatusChangeInterrupt,
}


impl From<CanState> for can::State {
    fn from(state: CanState) -> Self {
        match state {
            CanState::Initialization | CanState::Sleep => can::State::Disabled,
            CanState::Normal => can::State::Running,
            CanState::RunningError(err) => can::State::Error(err),
        }
    }
}

pub struct Can<'a> {
    registers: StaticRef<Registers>,
    clock: CanClock<'a>,
    can_state: Cell<CanState>,
    error_interrupt_counter: Cell<u32>,
    failed_messages: Cell<u32>,

    // communication params
    automatic_retransmission: Cell<bool>,
    //automatic_wake_up: Cell<bool>,
    operating_mode: OptionalCell<can::OperationMode>,
    bit_timing: OptionalCell<can::BitTiming>,

    // clients
    controller_client: OptionalCell<&'static dyn can::ControllerClient>,
    receive_client:
        OptionalCell<&'static dyn can::ReceiveClient< { can::STANDARD_CAN_PACKET_SIZE }>>,
    transmit_client:
        OptionalCell<&'static dyn can::TransmitClient< { can::STANDARD_CAN_PACKET_SIZE }>>,

    //buffers
    rx_buffer: TakeCell<'static, [u8; can::STANDARD_CAN_PACKET_SIZE]>,
    tx_buffer: TakeCell<'static, [u8; can::STANDARD_CAN_PACKET_SIZE]>,

    deferred_call: DeferredCall,

    //deffered call action task
    deferred_action: OptionalCell<AsyncAction>,
}

impl<'a> Can<'a> {
    pub fn new(registers: StaticRef<Registers>) -> Can<'a>{
        Can {    
            registers,
            enable_clock: fn(),
            can_state: Cell::new(CanState::Sleep),
            error_interrupt_counter: Cell::new(0),
            failed_messages: Cell::new(0),
            automatic_retransmission: Cell::new(false),
            //automatic_wake_up: Cell::new(false),
            operating_mode: OptionalCell::empty(),
            bit_timing: OptionalCell::empty(),
            controller_client: OptionalCell::empty(),
            receive_client: OptionalCell::empty(),
            transmit_client: OptionalCell::empty(),
            rx_buffer: TakeCell::empty(),
            tx_buffer: TakeCell::empty(),
            deferred_call: DeferredCall::new(),
            deferred_action: OptionalCell::empty(),
        }
    }

    /// This function is used for busy waiting and checks if the closure
    /// received as an argument returns a true value for `times` times.
    ///
    /// Usage: check is the INAK bit in the CAN_MSR is set for 200_000 times.
    /// ```ignore
    ///    Can::wait_for(200_000, || self.registers.can_msr.is_set(CAN_MSR::INAK))
    /// ```
    fn wait_for(times: usize, f: impl Fn() -> bool) -> bool {
        for _ in 0..times {
            if f() {
                return true;
            }
        }

        false
    }

    pub fn enable(&self) -> Result<(), kernel::ErrorCode> {
        //initialize the peripheral
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::INIT::SET);
        //we wait for init to be written as specified in rm0456 70.4.5
        if !Can::wait_for(20000, || self.registers.fdcan_cccr.is_set(FDCAN_CCCR::INIT)) {
            return Err(kernel::ErrorCode::FAIL);
        }
        //configuration change enable register
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::CCE::SET);

        self.can_state.set(CanState::Initialization);

        //we are doing a standard CAN driver for now, just making sure
        self.registers.fdcan_cccr.modify(FDCAN_CCCR::FDOE::CLEAR);

        //set comms mode
        
        // here we set it to overwrite if full on both RX FIFOs
        self.registers.fdcan_rxgfc.modify(FDCAN_RXGFC::F0OM::SET);
        self.registers.fdcan_rxgfc.modify(FDCAN_RXGFC::F1OM::SET);

        //set transmit order priority (fifo vs queue)
        self.registers.fdcan_txbc.modify(FDCAN_TXBC::TFQM::SET);

        match self.automatic_retransmission.get() {
            true => self.registers.fdcan_cccr.modify(FDCAN_CCCR::DAR::CLEAR),
            false => self.registers.fdcan_cccr.modify(FDCAN_CCCR::DAR::SET),
        }

        if let Some(operating_mode_settings) = self.operating_mode.get() {
            match operating_mode_settings {
                can::OperationMode::Monitoring => self.registers.fdcan_cccr.modify(FDCAN_CCCR::MON::SET),
                can::OperationMode::Loopback => {
                    self.registers.fdcan_cccr.modify(FDCAN_CCCR::TEST::SET);
                    self.registers.fdcan_test.modify(FDCAN_TEST::LBCK::SET);
                    self.registers.fdcan_cccr.modify(FDCAN_CCCR::MON::SET);
                }
                can::OperationMode::Freeze => return Err(kernel::ErrorCode::INVAL),
                _ => {}
            }
        }

        //we set bit timing mode
        if let Some(bit_timing_settings) = self.bit_timing.get() {
            self.registers.fdcan_nbtp.modify(FDCAN_NBTP::NTSEG1.val(bit_timing_settings.segment1 as u32));            
            self.registers.fdcan_nbtp.modify(FDCAN_NBTP::NTSEG2.val(bit_timing_settings.segment2 as u32));
            self.registers.fdcan_nbtp.modify(FDCAN_NBTP::NSJW.val(bit_timing_settings.sync_jump_width as u32));            
            self.registers.fdcan_nbtp.modify(FDCAN_DBTP::NBRP.val(bit_timing_settings.baud_rate_prescaler as u32));
        }
        else {
            self.enter_sleep_mode();
            return Err(kernel::ErrorCode::INVAL);
        }

        Ok(())
    }
}


