// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2026.

use core::cell::Cell;
use cortexm33::support;
use kernel::ErrorCode;
use kernel::hil;
use kernel::utilities::StaticRef;
use kernel::utilities::cells::OptionalCell;
use kernel::utilities::registers::interfaces::Writeable;
use kernel::utilities::registers::interfaces::{ReadWriteable, Readable};
use kernel::utilities::registers::{
    Field, ReadOnly, ReadWrite, register_bitfields, register_structs,
};

// Autogenerated by svd2regs.py
register_structs! {
    /// USB full speed
    UsbRegisters {
        /// USB endpoint/channel 0 register
        (0x000 => usb_chep0r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 1 register
        (0x004 => usb_chep1r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 2 register
        (0x008 => usb_chep2r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 3 register
        (0x00C => usb_chep3r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 4 register
        (0x010 => usb_chep4r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 5 register
        (0x014 => usb_chep5r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 6 register
        (0x018 => usb_chep6r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 7 register
        (0x01C => usb_chep7r: ReadWrite<u32, USB_CHEPXR::Register>),
        (0x020 => _reserved0),

        (0x040 => usb_cntr: ReadWrite<u32, USB_CNTR::Register>),
        /// USB interrupt status register
        (0x044 => usb_istr: ReadWrite<u32, USB_ISTR::Register>),
        /// USB frame number register
        (0x048 => usb_fnr: ReadWrite<u32, USB_FNR::Register>),
        /// USB_DADDR
        (0x04C => usb_daddr: ReadWrite<u32, USB_DADDR::Register>),
        (0x050 => _reserved1),
        /// USB_LPMCSR
        (0x054 => usb_lpmcsr: ReadWrite<u32, USB_LPMCSR::Register>),
        /// USB_BCDR
        (0x058 => usb_bcdr: ReadWrite<u32, USB_BCDR::Register>),
        (0x05C => @END),
    }
}
register_bitfields![u32,
USB_CHEPXR [
    /// endpoint/channel address
    EA OFFSET(0) NUMBITS(4) [],
    /// Status bits, for transmission transfers
    STATTX OFFSET(4) NUMBITS(2) [
        // Added manually:
        Disabled = 0b00,
        Stall = 0b01,
        Nak = 0b10,
        Valid = 0b11,
    ],
    /// Data toggle, for transmission transfers
    DTOGTX OFFSET(6) NUMBITS(1) [],
    /// Valid USB transaction transmitted
    VTTX OFFSET(7) NUMBITS(1) [],
    /// endpoint/channel kind
    EPKIND OFFSET(8) NUMBITS(1) [],
    /// USB type of transaction
    UTYPE OFFSET(9) NUMBITS(2) [
        // Added manually:
        Bulk = 0b00,
        Control = 0b01,
        Iso = 0b10,
        Interrupt = 0b11,
    ],
    /// Setup transaction completed
    SETUP OFFSET(11) NUMBITS(1) [],
    /// Status bits, for reception transfers
    STATRX OFFSET(12) NUMBITS(2) [
        // Added manually:
        Disabled = 0b00,
        Stall = 0b01,
        Nak = 0b10,
        Valid = 0b11,
    ],
    /// Data Toggle, for reception transfers
    DTOGRX OFFSET(14) NUMBITS(1) [],
    /// USB valid transaction received
    VTRX OFFSET(15) NUMBITS(1) [],
    /// Host mode
    DEVADDR OFFSET(16) NUMBITS(7) [],
    /// Host mode
    NAK OFFSET(23) NUMBITS(1) [],
    /// Low speed endpoint  host with HUB only
    LS_EP OFFSET(24) NUMBITS(1) [
        /// Full speed endpoint
        FullSpeedEndpoint = 0,
        /// Low speed endpoint
        LowSpeedEndpoint = 1
    ],
    /// Received error for an OUT/SETUP transaction
    ERR_TX OFFSET(25) NUMBITS(1) [],
    /// Received error for an IN transaction
    ERR_RX OFFSET(26) NUMBITS(1) [],
    /// Three errors for an OUT or SETUP transaction
    THREE_ERR_TX OFFSET(27) NUMBITS(2) [
        /// Less than 3 errors received.
        LessThan3ErrorsReceived = 0,
        /// More than 3 errors received, last error is timeout error.
        MoreThan3ErrorsReceivedLastErrorIsTimeoutError = 1,
        /// More than 3 errors received, last error is data error (CRC error).
        MoreThan3ErrorsReceivedLastErrorIsDataErrorCRCError = 2,
        /// More than 3 errors received, last error is protocol error (invalid PID, false EOP, bitstuffing error, SYNC error).
        B_0x3 = 3
    ],
    /// Three errors for an IN transaction
    THREE_ERR_RX OFFSET(29) NUMBITS(2) [
        /// Less than 3 errors received.
        LessThan3ErrorsReceived = 0,
        /// More than 3 errors received, last error is timeout error.
        MoreThan3ErrorsReceivedLastErrorIsTimeoutError = 1,
        /// More than 3 errors received, last error is data error (CRC error).
        MoreThan3ErrorsReceivedLastErrorIsDataErrorCRCError = 2,
        /// More than 3 errors received, last error is protocol error (invalid PID, false EOP, bitstuffing error, SYNC error).
        B_0x3 = 3
    ]
],
USB_CNTR [
    /// USB Reset
    USBRST OFFSET(0) NUMBITS(1) [
        /// No effect
        NoEffect = 0,
        /// USB core is under reset
        USBCoreIsUnderReset = 1
    ],
    /// Power down
    PDWN OFFSET(1) NUMBITS(1) [
        /// Exit power down.
        ExitPowerDown = 0,
        /// Enter power down mode.
        EnterPowerDownMode = 1
    ],
    /// Suspend state effective
    SUSPRDY OFFSET(2) NUMBITS(1) [
        /// Normal operation
        NormalOperation = 0,
        /// Suspend state
        SuspendState = 1
    ],
    /// Suspend state enable
    SUSPEN OFFSET(3) NUMBITS(1) [
        /// No effect.
        NoEffect = 0,
        /// Enter L1/L2 suspend
        EnterL1L2Suspend = 1
    ],
    /// L2 remote wakeup / resume driver
    L2RES OFFSET(4) NUMBITS(1) [
        /// No effect
        NoEffect = 0,
        /// Send L2 resume signaling to device
        SendL2ResumeSignalingToDevice = 1
    ],
    /// L1 remote wakeup / resume driver
    L1RES OFFSET(5) NUMBITS(1) [
        /// No effect
        NoEffect = 0,
        /// Send 50 us remote-wakeup signaling to host
        Send50UsRemoteWakeupSignalingToHost = 1
    ],
    /// LPM L1 state request interrupt mask
    L1REQM OFFSET(7) NUMBITS(1) [
        /// LPM L1 state request (L1REQ) interrupt disabled.
        LPML1StateRequestL1REQInterruptDisabled = 0,
        /// L1REQ interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Expected start of frame interrupt mask
    ESOFM OFFSET(8) NUMBITS(1) [
        /// Expected start of frame (ESOF) interrupt disabled.
        ExpectedStartOfFrameESOFInterruptDisabled = 0,
        /// ESOF interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Start of frame interrupt mask
    SOFM OFFSET(9) NUMBITS(1) [
        /// SOF interrupt disabled.
        SOFInterruptDisabled = 0,
        /// SOF interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// USB reset request (Device mode) or device connect/disconnect (Host mode) interrupt mask
    RST_DCONM OFFSET(10) NUMBITS(1) [
        /// RESET interrupt disabled.
        RESETInterruptDisabled = 0,
        /// RESET interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Suspend mode interrupt mask
    SUSPM OFFSET(11) NUMBITS(1) [
        /// Suspend mode request (SUSP) interrupt disabled.
        SuspendModeRequestSUSPInterruptDisabled = 0,
        /// SUSP interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Wakeup interrupt mask
    WKUPM OFFSET(12) NUMBITS(1) [
        /// WKUP interrupt disabled.
        WKUPInterruptDisabled = 0,
        /// WKUP interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Error interrupt mask
    ERRM OFFSET(13) NUMBITS(1) [
        /// ERR interrupt disabled.
        ERRInterruptDisabled = 0,
        /// ERR interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Packet memory area over / underrun interrupt mask
    PMAOVRM OFFSET(14) NUMBITS(1) [
        /// PMAOVR interrupt disabled.
        PMAOVRInterruptDisabled = 0,
        /// PMAOVR interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Correct transfer interrupt mask
    CTRM OFFSET(15) NUMBITS(1) [
        /// Correct transfer (CTR) interrupt disabled.
        CorrectTransferCTRInterruptDisabled = 0,
        /// CTR interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// 512 byte threshold interrupt mask
    THR512M OFFSET(16) NUMBITS(1) [
        /// 512 byte threshold interrupt disabled
        _512ByteThresholdInterruptDisabled = 0,
        /// 512 byte threshold interrupt enabled
        _512ByteThresholdInterruptEnabled = 1
    ],
    /// Device disconnection mask
    DDISCM OFFSET(17) NUMBITS(1) [
        /// Device disconnection interrupt disabled
        DeviceDisconnectionInterruptDisabled = 0,
        /// Device disconnection interrupt enabled
        DeviceDisconnectionInterruptEnabled = 1
    ],
    /// HOST mode
    HOST OFFSET(31) NUMBITS(1) [
        /// USB Device function
        USBDeviceFunction = 0,
        /// USB host function
        USBHostFunction = 1
    ]
],
USB_ISTR [
    /// Device Endpoint / host channel identification number
    IDN OFFSET(0) NUMBITS(4) [],
    /// Direction of transaction
    DIR OFFSET(4) NUMBITS(1) [],
    /// LPM L1 state request
    L1REQ OFFSET(7) NUMBITS(1) [],
    /// Expected start of frame
    ESOF OFFSET(8) NUMBITS(1) [],
    /// Start of frame
    SOF OFFSET(9) NUMBITS(1) [],
    /// USB reset request (Device mode) or device connect/disconnect (Host mode)
    RST_DCON OFFSET(10) NUMBITS(1) [],
    /// Suspend mode request
    SUSP OFFSET(11) NUMBITS(1) [],
    /// Wakeup
    WKUP OFFSET(12) NUMBITS(1) [],
    /// Error
    ERR OFFSET(13) NUMBITS(1) [],
    /// Packet memory area over / underrun
    PMAOVR OFFSET(14) NUMBITS(1) [],
    /// Completed transfer in host mode
    CTR OFFSET(15) NUMBITS(1) [],
    /// 512 byte threshold interrupt
    THR512 OFFSET(16) NUMBITS(1) [],
    /// Device connection
    DDISC OFFSET(17) NUMBITS(1) [],
    /// Device connection status
    DCON_STAT OFFSET(29) NUMBITS(1) [
        /// No device connected
        NoDeviceConnected = 0,
        /// FS or LS device connected to the host
        FSOrLSDeviceConnectedToTheHost = 1
    ],
    /// Low speed device connected
    LS_DCON OFFSET(30) NUMBITS(1) []
],
USB_FNR [
    /// Frame number
    FN OFFSET(0) NUMBITS(11) [],
    /// Lost SOF
    LSOF OFFSET(11) NUMBITS(2) [],
    /// Locked
    LCK OFFSET(13) NUMBITS(1) [],
    /// Receive dataline status
    RXDM OFFSET(14) NUMBITS(1) [],
    /// Receive data + line status
    RXDP OFFSET(15) NUMBITS(1) []
],
USB_DADDR [
    /// Device address
    ADD OFFSET(0) NUMBITS(7) [],
    /// Enable function
    EF OFFSET(7) NUMBITS(1) []
],
USB_LPMCSR [
    /// LPM support enable
    LPMEN OFFSET(0) NUMBITS(1) [],
    /// LPM token acknowledge enable
    LPMACK OFFSET(1) NUMBITS(1) [
        /// the valid LPM token is NYET.
        TheValidLPMTokenIsNYET = 0,
        /// the valid LPM token is ACK.
        TheValidLPMTokenIsACK = 1
    ],
    /// bRemoteWake value
    REMWAKE OFFSET(3) NUMBITS(1) [],
    /// BESL value
    BESL OFFSET(4) NUMBITS(4) []
],
USB_BCDR [
    /// Battery charging detector (BCD) enable
    BCDEN OFFSET(0) NUMBITS(1) [],
    /// Data contact detection (DCD) mode enable
    DCDEN OFFSET(1) NUMBITS(1) [],
    /// Primary detection (PD) mode enable
    PDEN OFFSET(2) NUMBITS(1) [],
    /// Secondary detection (SD) mode enable
    SDEN OFFSET(3) NUMBITS(1) [],
    /// Data contact detection (DCD) status
    DCDET OFFSET(4) NUMBITS(1) [
        /// data lines contact not detected.
        DataLinesContactNotDetected = 0,
        /// data lines contact detected.
        DataLinesContactDetected = 1
    ],
    /// Primary detection (PD) status
    PDET OFFSET(5) NUMBITS(1) [
        /// no BCD support detected (connected to SDP or proprietary device).
        NoBCDSupportDetectedConnectedToSDPOrProprietaryDevice = 0,
        /// BCD support detected (connected to ACA, CDP or DCP).
        BCDSupportDetectedConnectedToACACDPOrDCP = 1
    ],
    /// Secondary detection (SD) status
    SDET OFFSET(6) NUMBITS(1) [
        /// CDP detected.
        CDPDetected = 0,
        /// DCP detected.
        DCPDetected = 1
    ],
    /// DM pull-up detection status
    PS2DET OFFSET(7) NUMBITS(1) [
        /// Normal port detected (connected to SDP, ACA, CDP or DCP).
        NormalPortDetectedConnectedToSDPACACDPOrDCP = 0,
        /// PS2 port or proprietary charger detected.
        PS2PortOrProprietaryChargerDetected = 1
    ],
    /// DP pull-up / DPDM pull-down
    DPPU_DPD OFFSET(15) NUMBITS(1) []
]
];
const USB_BASE: StaticRef<UsbRegisters> =
    unsafe { StaticRef::new(0x40016000 as *const UsbRegisters) };

pub struct Usbd<'a> {
    registers: StaticRef<UsbRegisters>,
    client: OptionalCell<&'a dyn hil::usb::Client<'a>>,
}

impl Usbd<'_> {
    pub const fn new() -> Self {
        Self {
            registers: USB_BASE,
            client: OptionalCell::empty(),
        }
    }

    pub fn enable(&self) {
        kernel::debug!("Usbd enable start");

        // Exit power-down and reset the USB peripheral
        self.registers.usb_cntr.write(USB_CNTR::PDWN::ExitPowerDown);

        // We need a delay of (at least) t_STARTUP=1us
        let sys_freq = unsafe { crate::rcc::get_freqs().sys.unwrap() };
        let nop_count = (sys_freq / 1_000_000_u32).0;
        for _ in 0..nop_count {
            support::nop();
        }

        self.registers.usb_cntr.write(
            USB_CNTR::PDWN::ExitPowerDown
                + USB_CNTR::RST_DCONM::SET // "Reset request" interrupt
                + USB_CNTR::SUSPM::SET // "Suspend mode" interrupt
                + USB_CNTR::WKUPM::SET // "Wake-up" interrupt
                + USB_CNTR::CTRM::SET, // "Correct transfer" (CTR) interrupt
        );

        self.registers.usb_bcdr.write(USB_BCDR::DPPU_DPD::SET);

        kernel::debug!("Usbd enable end");
    }

    pub fn handle_interrupt(&self) {
        // kernel::debug!("USB interrupt: {:08X}", self.registers.usb_istr.get(),);

        if self.registers.usb_istr.is_set(USB_ISTR::SUSP) {
            self.registers.usb_istr.modify(USB_ISTR::SUSP::CLEAR);
            // kernel::debug!("    suspend");
        }

        if self.registers.usb_istr.is_set(USB_ISTR::WKUP) {
            self.registers.usb_istr.modify(USB_ISTR::WKUP::CLEAR);
            kernel::debug!("    wakeup");
        }

        if self.registers.usb_istr.is_set(USB_ISTR::RST_DCON) {
            self.registers.usb_istr.modify(USB_ISTR::RST_DCON::CLEAR);
            kernel::debug!("    dcon");

            self.registers
                .usb_daddr
                .write(USB_DADDR::EF::SET + USB_DADDR::ADD.val(0));

            self.registers.usb_chep0r.write(
                USB_CHEPXR::UTYPE::Control + USB_CHEPXR::STATRX::Nak + USB_CHEPXR::STATTX::Nak,
            );

            let endpoint_registers = [
                &self.registers.usb_chep0r,
                &self.registers.usb_chep1r,
                &self.registers.usb_chep2r,
                &self.registers.usb_chep3r,
                &self.registers.usb_chep4r,
                &self.registers.usb_chep5r,
                &self.registers.usb_chep6r,
                &self.registers.usb_chep7r,
            ];

            for i in 1..endpoint_registers.len() {
                let usb_chepxr = endpoint_registers[i];
                usb_chepxr.write(USB_CHEPXR::EA.val(i as u32) + USB_CHEPXR::UTYPE::Bulk);
            }
        }

        if self.registers.usb_istr.is_set(USB_ISTR::CTR) {
            kernel::debug!("    ctr");
        }
    }
}
